# ----
# Site
title: Doce Low Carb
url: "https://docelowcarb.com.br"
baseurl: ""
google_analytics_key: "UA-114647994-1"
newsletter_action: 
disqus_shortname: docevidalowcarb

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Doce Low Carb é um blog onde compartilho a deliciosa experiência de criar receitas Low Carb, Paleo e Keto Cetogênica. Venha conhecer esse prazeroso estilo de alimentação saudável que está mudando minha vida!
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: Doce Low Carb
  links:
    - https://github.com/CloudCannon/treat-jekyll-template

# -----
# Build

paginate: 10
paginate_path: "/:num/"
permalink: pretty

collections:
  stories:
    output: true      

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      push_sidebar_down: true
      print_stylesheet: true
      comments: true
      _options:
        content:
          width: 1560
          height: 2000
        featured_image:
          width: 1560
          height: 2000
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
      push_sidebar_down: true

compress_images:
  images_path: "images/**/*.{gif,png,jpg,jpeg,svg}"
  
sass:
  style: compressed
  
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-youtube

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS

_options:
  author_image:
    width: 200
    height: 200