# ----
# Site
title: Doce Low Carb
url: "https://docelowcarb.com.br"
baseurl: ""
google_analytics_key: "UA-114647994-1"
email: fabiola.analytics@gmail.com
newsletter_action: 
disqus_shortname: docevidalowcarb
analytics_id: "UA-114647994-1"

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Doce Low Carb é um blog onde compartilho a deliciosa experiência de criar receitas Low Carb, Paleo e Keto Cetogênica. Venha conhecer esse prazeroso estilo de alimentação saudável que está mudando minha vida!
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: Doce Low Carb
  links:
    - https://github.com/CloudCannon/treat-jekyll-template
    
name: 'Fabí'
bio: > 
    Olá sou a Fabí! Criei o Blog Doce Low Carb para compartilhar minhas receitas low carb preferidas e falar sobre esse prazeroso estilo de alimentação saudável que mudou minha vida. Confira novidades também nas minhas redes sociais!
author_image: "/images/fabi-low-carb-diet.jpeg"
twitter_username: fabiola_faria
github_username:  fabiolafaria
facebook_username: docelowcarb
instagram_username: fabilowcarb
pinterest_username: docelowcarb

# -----
# Build

paginate: 10
paginate_path: "/:num/"
permalink: /:title/

collections:
  stories:
    output: true      

compress_images:
  images_path: "images/**/*.{gif,png,jpg,jpeg,svg}"
  
mini_magick:
	thumbnail:
		source: uploads/
		destination: uploads/thumbs
		resize: "60x60"
  
sass:
  style: compressed
  
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-compose
  - jekyll-minimagick

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
  
lsi: true

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS

_options:
  author_image:
    width: 200
    height: 200